add_executable(ch43_91_challenge_tests main.cpp)
target_link_libraries(ch43_91_challenge_tests PRIVATE labstest)
add_test(NAME ch43_91_challenge COMMAND ch43_91_challenge_tests)

add_executable(ch43_91_challenge_runner challenge_runner.cpp)
add_test(NAME ch43_91_challenge_runner_help COMMAND ch43_91_challenge_runner)
