#define LABSTEST_MAIN
#include "labstest.hpp"

#include <cstdint>
#include <vector>

#include "nesboot.hpp"

using namespace nesboot;

namespace {

// Byte-for-byte duplicate of tests/public/ch20_nes_bus_cartridges/roms/
// boot_success.nes (generated by 02_ines_nrom/tools/gen_fixtures.py, see
// provenance.md) so the suite stays self-contained.
const std::vector<uint8_t> kBootRom = [] {
    const uint8_t code[] = {
        0x78,                   // SEI
        0xD8,                   // CLD
        0xA2, 0xFF,             // LDX #$FF
        0x9A,                   // TXS
        0xA9, 0x77,             // LDA #$77
        0x85, 0x02,             // STA $02   <- success code
        0xA9, 0x55,             // LDA #$55
        0x85, 0x03,             // STA $03   <- witness cell
        0xE6, 0x04,             // INC $04   <- heartbeat
        0x4C, 0x0D, 0x80,       // JMP $800D
    };
    std::vector<uint8_t> prg(code, code + sizeof code);
    prg.resize(16384 - 6, 0xFF);
    const uint8_t vectors[] = {0x00, 0x80, 0x00, 0x80, 0x00, 0x80};
    prg.insert(prg.end(), vectors, vectors + 6);

    std::vector<uint8_t> rom(16, 0);
    rom[0] = 'N'; rom[1] = 'E'; rom[2] = 'S'; rom[3] = 0x1A;
    rom[4] = 1; rom[5] = 1;
    rom.insert(rom.end(), prg.begin(), prg.end());
    rom.resize(16 + 16384 + 8192, 0x00);
    return rom;
}();

struct Rig {
    Bus bus;
    Cpu cpu{.bus = &bus};

    Rig() {
        EXPECT_TRUE(load_ines(bus, kBootRom));
    }
};

}  // namespace

TEST(boot, reset_vector_comes_from_the_cartridge) {
    Rig r;
    reset(r.cpu);
    EXPECT_EQ(r.cpu.pc, 0x8000);       // answered by PRG through $FFFC
    EXPECT_EQ(r.cpu.sp, 0xFA);
}

TEST(boot, boots_and_writes_the_success_code_to_ram) {
    Rig r;
    boot(r.bus, r.cpu, 500);
    EXPECT_FALSE(r.cpu.halted);        // loops forever on INC — alive
    EXPECT_EQ(r.bus.ram[0x02], 0x77);  // THE success code
    EXPECT_EQ(r.bus.ram[0x03], 0x55);
}

TEST(boot, heartbeat_counter_increments_while_looping) {
    Rig r;
    boot(r.bus, r.cpu, 200);
    EXPECT_TRUE(r.bus.ram[0x04] > 0);     // RMW loop ran at least once

    Rig r2;
    boot(r2.bus, r2.cpu, 600);
    EXPECT_TRUE(r2.bus.ram[0x04] > r.bus.ram[0x04]);   // keeps counting
}

TEST(boot, unknown_opcode_jams_the_rig_loudly) {
    Bus bus;
    Cpu cpu{.bus = &bus};
    struct JamCart final : Mapper {
        uint8_t cpu_read(uint16_t addr) override {
            return addr >= 0x8000 ? 0xFF : 0;
        }
        void cpu_write(uint16_t, uint8_t) override {}
    } cart;
    bus.cartridge = &cart;
    reset(cpu);
    cpu.pc = 0x8000;                   // land on the JAM opcode
    step(cpu);
    EXPECT_TRUE(cpu.halted);
}
