#pragma once
#include <cstdint>

// Golden FNV-1a 64 digest of the 4000-frame jingle render (8000 s16le
// samples). Generated by the reference solution; see tests/public/
// ch47_ps1_spu/goldens/provenance.md for the generating command.
namespace spu {
inline constexpr uint64_t kGoldenJinglePcmFnv64 = 0x65781DCA7BF9338DULL;
}
