#pragma once
#include <cstdint>

// Golden FNV-1a 64 hash of the boot_handshake EVENT LOG, generated by the
// reference solution (run twice, byte-identical) via:
//
//   ch49_03_boot_runner_runner --rom boot_handshake.bin --cycles 40000 \
//       --hash-frame ev.log --headless
//
// Regeneration command documented in tests/public/ch49_ps1_system_scheduling/
// goldens/provenance.md.
namespace ps1sys {

constexpr uint64_t kGoldenBootHandshakeFnv64 = 0x760C13EA4039747Cull;

}  // namespace ps1sys
