#define LABSTEST_MAIN
#include "labstest.hpp"

#include <cstdint>

#include "bg_pipeline.hpp"

using namespace nes21bg;

namespace {

// FNV-1a 64 — same digest the hidden manifests use for golden frames.
uint64_t fnv1a64(const uint8_t* data, size_t n) {
    uint64_t h = 0xCBF29CE484222325ULL;
    for (size_t i = 0; i < n; ++i) {
        h ^= data[i];
        h *= 0x100000001B3ULL;
    }
    return h;
}

// Golden FNV-1a64 of the crafted scene below, generated by the reference
// solution and pinned here (value filled from the solution run; see README).
constexpr uint64_t kGoldenFrameFNV = 0x167CF46A84642705ULL;

struct CraftedScene {
    std::array<uint8_t, 0x2000> chr{};
    std::array<uint8_t, 0x0800> nt{};
    std::array<uint8_t, 0x0020> pal{};
};

// Tile 1: top row tile-color 3, other rows tile-color 2 (plane 1 only).
// Tile 2: vertical stripes, colors 1/2 alternating per pixel column.
void craft_tiles(CraftedScene& s) {
    for (int y = 0; y < 8; ++y) {
        if (y == 0) {
            s.chr[1 * 16 + y] = 0xFF;
            s.chr[1 * 16 + 8 + y] = 0xFF;
        } else {
            s.chr[1 * 16 + y] = 0x00;
            s.chr[1 * 16 + 8 + y] = 0xFF;
        }
    }
    for (int x = 0; x < 8; ++x) {
        uint8_t bit = uint8_t(1u << (7 - x));
        uint8_t plane0 = (x % 2 == 0) ? bit : uint8_t(0);
        uint8_t plane1 = (x % 2 == 0) ? uint8_t(0) : bit;
        for (int y = 0; y < 8; ++y) {
            s.chr[2 * 16 + y] |= plane0;
            s.chr[2 * 16 + 8 + y] |= plane1;
        }
    }
}

}  // namespace

TEST(nes21bg, attribute_quadrants) {
    // Quadrant bits: 0=top-left, 1=top-right, 2=bottom-left, 3=bottom-right
    // of each 2x2-tile block; one attribute byte covers 4x4 tiles.
    uint8_t at = uint8_t((0 << 0) | (1 << 2) | (2 << 4) | (3 << 6));  // 0xE4
    EXPECT_EQ(attribute_bits(at, 0, 0), 0);
    EXPECT_EQ(attribute_bits(at, 3, 0), 1);
    EXPECT_EQ(attribute_bits(at, 0, 3), 2);
    EXPECT_EQ(attribute_bits(at, 3, 3), 3);
    EXPECT_EQ(attribute_bits(at, 2, 1), 1);   // right half of top quadrants
    EXPECT_EQ(attribute_bits(at, 1, 2), 2);   // left half of bottom quadrants
}

TEST(nes21bg, attribute_uses_coarse_tile_coords) {
    // Same quadrant answer regardless of fine position within the tile.
    uint8_t at = 0b00'10'01'11 & 0xFF;
    EXPECT_EQ(attribute_bits(at, 9, 17), (at >> ((17 & 2) << 1 | 9 & 2)) & 3);
    EXPECT_EQ(attribute_bits(0xFF, 5, 5), 3);
    EXPECT_EQ(attribute_bits(0x00, 31, 31), 0);
}

TEST(nes21bg, tile_pixel_planar_decode) {
    uint8_t low = 0b10110000;
    uint8_t high = 0b01000000;
    EXPECT_EQ(tile_pixel(low, high, 0), 1);   // bit7: low=1, high=0
    EXPECT_EQ(tile_pixel(low, high, 1), 2);   // bit6: low=0, high=1
    EXPECT_EQ(tile_pixel(low, high, 2), 1);
    EXPECT_EQ(tile_pixel(low, high, 3), 1);
    EXPECT_EQ(tile_pixel(low, high, 4), 0);   // transparent
    EXPECT_EQ(tile_pixel(0xFF, 0xFF, 6), 3);
}

TEST(nes21bg, render_pixel_selects_pattern_table_by_ctrl) {
    CraftedScene s;
    craft_tiles(s);
    s.nt[0] = 2;  // top-left tile = stripes
    FrameInputs in{s.chr.data(), s.nt.data(), s.pal.data(), 0x00};
    EXPECT_EQ(render_pixel(in, 0, 0), 1);
    EXPECT_EQ(render_pixel(in, 1, 0), 2);

    // Same tile index in the second pattern table must be blank here,
    // so the pixel falls back to the backdrop (index 0).
    FrameInputs in_hi{s.chr.data(), s.nt.data(), s.pal.data(), 0x10};
    s.chr[0x1000 + 2 * 16] = 0x00;
    s.chr[0x1000 + 2 * 16 + 8] = 0x00;
    EXPECT_EQ(render_pixel(in_hi, 0, 0), 0);
}

TEST(nes21bg, render_pixel_backdrop_rule) {
    CraftedScene s;
    craft_tiles(s);
    s.nt[0] = 1;                       // tile 1 rows 1-7 are transparent
    s.pal[0x00] = 0x0F;                // backdrop = black
    s.pal[0x05] = 0x21;                // palette 1 color 1 = blue-ish
    FrameInputs in{s.chr.data(), s.nt.data(), s.pal.data(), 0x00};
    EXPECT_EQ(render_pixel(in, 0, 0), (0 << 2) | 3);  // row 0 opaque
    EXPECT_EQ(render_pixel(in, 0, 9), 0x00);          // row 1 -> backdrop
}

TEST(nes21bg, crafted_frame_golden_hash) {
    CraftedScene s;
    craft_tiles(s);
    // Tile map: row 0 = tiles 1,2 alternating; attributes split quadrants.
    for (int i = 0; i < 32; ++i) s.nt[i] = uint8_t((i % 2) ? 2 : 1);
    for (int r = 1; r < 30; ++r)
        for (int c = 0; c < 32; ++c) s.nt[r * 32 + c] = uint8_t((c / 4) % 2 ? 2 : 1);
    s.nt[0x3C0] = 0xE4;  // four different palettes across the first block
    for (int p = 0; p < 4; ++p) {
        s.pal[p * 4 + 1] = uint8_t(0x11 + p * 4);
        s.pal[p * 4 + 2] = uint8_t(0x21 + p * 4);
        s.pal[p * 4 + 3] = uint8_t(0x2A);
    }
    s.pal[0x00] = 0x0F;

    std::array<uint8_t, 256u * 240u * 4> frame{};
    FrameInputs in{s.chr.data(), s.nt.data(), s.pal.data(), 0x00};
    render_frame(frame, in);
    // Golden FNV-1a64 generated by the reference solution (run twice,
    // identical); see README "Verification".
    EXPECT_EQ(fnv1a64(frame.data(), frame.size()), kGoldenFrameFNV);
}
