// Challenge: deterministic audio hash. Mix a scripted PSG arpeggio with
// Direct Sound FIFO playback, render PCM, and verify the committed FNV-64.
#define LABSTEST_MAIN
#include <string>
#include <vector>
#include "../01_psg_mix/psg.hpp"
#include "../02_direct_sound/dsound.hpp"
#include "labstest.hpp"
#include <cstdio>

using namespace gba;

namespace {

// Render 256 frames: PSG square via duty table at a fixed phase step,
// noise via LFSR, plus two Direct Sound FIFOs filled from fixed ramps.
u64 render_scene(std::vector<u16>* pcm_out) {
    SoundFifo fifo_a, fifo_b;
    fifo_a.reset();
    fifo_b.reset();
    for (int i = 0; i < kFifoSize; ++i) {
        fifo_a.push(u8(i * 3));
        fifo_b.push(u8(200 - i * 2));
    }

    u16 lfsr = 0x7FFF;
    std::vector<u16> pcm;
    pcm.reserve(256);
    int phase = 0;
    for (int frame = 0; frame < 256; ++frame) {
        bool high = psg_duty_high(2, phase >> 5);
        phase = (phase + 7) & 0xFF;
        int psg = high ? 10 : -10;
        if (frame % 16 == 0) psg += lfsr_step(lfsr, false) ? 4 : -4;
        int vol_env = envelope_volume(12, 4, 0, frame / 8);
        int mixed =
            psg * vol_env / 15 +
            apply_dsound_volume(fifo_a.pop(), 1) +
            apply_dsound_volume(fifo_b.pop(), 0) * 2;
        pcm.push_back(bias_quantize(mixed, u16(512 | (2 << 14))));
    }
    u64 h = fnv64(pcm.data(), pcm.size() * sizeof(u16));
    if (pcm_out) *pcm_out = pcm;
    return h;
}

}  // namespace

TEST(challenge, audio_digest_deterministic_and_golden) {
    std::vector<u16> a, b;
    u64 h1 = render_scene(&a);
    u64 h2 = render_scene(&b);
    EXPECT_EQ(h1, h2);
    EXPECT_TRUE(a == b);

    char buf[32];
    std::snprintf(buf, sizeof(buf), "%016llX", (unsigned long long)h1);
    // Golden generated by the reference solution (see provenance.md).
    EXPECT_EQ(std::string(buf), "2550657C798F36FD");
}
