#pragma once
#include <cstdint>

namespace sio {

// Golden FNV-1a 64 digest of the 91_challenge round-trip read-back bytes.
// Generated by the reference solution, run twice, byte-identical; see
// tests/public/ch48_ps1_controllers_memcards/goldens/provenance.md.
constexpr uint64_t kGoldenRoundtripFnv64 = 0x94CC2D4313924309ULL;

}  // namespace sio
