#define LABSTEST_MAIN
#include "labstest.hpp"
#include "machine.hpp"
#include "frame_io.hpp"

#include <string>
#include <vector>

// Challenge acceptance trio: display test / keypad test / beep test.
// All fixtures are course-original programs assembled for this chapter
// (see fixtures/*.asm.txt). Goldens were generated by the reference
// solution runner; provenance.md records the exact commands.

namespace {

chip8::Machine loaded(const std::vector<uint8_t>& image) {
    chip8::Machine m;
    m.load(image);
    return m;
}

}  // namespace

TEST(challenge_display, stripes_hash_matches_golden) {
    // Same program as fixtures/display_test.bin: 15-row 0xAA stripes at
    // every even column.
    std::vector<uint8_t> image = {
        0xA2,0x20, 0x60,0x00, 0xD0,0x1F, 0x70,0x02,
        0x30,0x40, 0x12,0x04, 0x12,0x0C,
    };
    image.resize(0x20, 0x00);            // pad to rom offset of the sprite
    for (int k = 0; k < 15; ++k)         // stripe sprite at 0x220
        image.push_back(0xAA);

    chip8::Machine m = loaded(image);
    m.run(chip8::kCyclesPerFrame * 2);
    EXPECT_TRUE(m.display.get(0, 0));
    EXPECT_TRUE(m.display.get(14, 14));  // stripe column 14 reaches row 14
    EXPECT_FALSE(m.display.get(1, 0));
    EXPECT_EQ(chip8::frame_hash_hex(m.display), "2FFFC7BF7D608CB5");
}

TEST(challenge_keypad, eight_presses_plot_expected_pattern) {
    // Same program as fixtures/keypad_test.bin: one DT-paced sample per
    // press; plots a dot at (column, key*2), column advances by 4.
    std::vector<uint8_t> image = {
        0x6E,0x08, 0x62,0x00, 0xA2,0x22,
        0xF0,0x0A, 0x83,0x00, 0x83,0x0E,
        0xD2,0x31, 0x72,0x04, 0x65,0x02, 0xF5,0x15,
        0x67,0x00, 0xF7,0x07, 0x37,0x00, 0x12,0x14,
        0x32,0x20, 0x12,0x06, 0x12,0x20,
    };
    image.resize(0x22, 0x00);
    image.push_back(0x80);               // dot sprite at 0x222

    chip8::InputFeed feed = chip8::InputFeed::from_lines({
        ".", ".",
        "4", ".", ".", ".",
        "B", ".", ".", ".",
        "6", ".", ".", ".",
        "1", ".", ".", ".",
        "D", ".", ".", ".",
        "3", ".", ".", ".",
        "8", ".", ".", ".",
        "E", ".", ".", ".",
        ".", ".", ".", ".", ".", ".", ".", ".",
    });

    chip8::Machine m = loaded(image);
    for (std::size_t f = 0; f < 48; ++f) {
        feed.apply(m.keypad, f);
        m.run(chip8::kCyclesPerFrame);
    }
    EXPECT_EQ(m.pc, 0x220);              // halted after 8 samples
    int lit = 0;
    for (int y = 0; y < chip8::kHeight; ++y)
        for (int x = 0; x < chip8::kWidth; ++x)
            if (m.display.get(x, y)) ++lit;
    EXPECT_EQ(lit, 8);                   // exactly one dot per press
    EXPECT_TRUE(m.display.get(0, 8));    // key 4 in column 0
    EXPECT_TRUE(m.display.get(28, 28));  // key E in the last column
    EXPECT_EQ(chip8::frame_hash_hex(m.display), "092B3214C73A0A05");
}

TEST(challenge_beep, beep_log_and_final_frame_match_golden) {
    // Same program as fixtures/beep_test.bin: ST=3 beep while a dot trail
    // marches along y=10 at x=DT (5..0), then a marker at (0,20).
    std::vector<uint8_t> image = {
        0x67,0x05, 0x62,0x0A, 0xA2,0x2A,
        0x68,0x03, 0xF8,0x18, 0x63,0x06, 0xF7,0x15,
        0xF0,0x07, 0x90,0x30, 0x12,0x0E,
        0xD0,0x21, 0x83,0x00, 0xF0,0x07, 0x30,0x00, 0x12,0x0E,
        0x62,0x14, 0xD0,0x21, 0x12,0x22,
    };
    image.resize(0x2A, 0x00);
    image.push_back(0x80);               // dot sprite at 0x22A

    std::vector<bool> events;
    chip8::Machine m = loaded(image);
    m.timers.on_beep = [&](bool started) { events.push_back(started); };

    for (int f = 0; f < 16; ++f)
        m.run(chip8::kCyclesPerFrame);

    EXPECT_TRUE(events.size() >= static_cast<std::size_t>(2));
    EXPECT_TRUE(events.front());         // beep started when ST was set
    EXPECT_FALSE(events.back());         // and ended before the halt

    int starts = 0, ends = 0;
    for (bool e : events) (e ? starts : ends)++;
    EXPECT_EQ(starts, 1);
    EXPECT_EQ(ends, 1);

    // Trail dots at (5..0, 10) plus marker at (0,20).
    EXPECT_TRUE(m.display.get(5, 10));
    EXPECT_TRUE(m.display.get(0, 10));
    EXPECT_TRUE(m.display.get(0, 20));
    EXPECT_EQ(m.pc, 0x222);
    EXPECT_EQ(chip8::frame_hash_hex(m.display), "18F166968F89B029");
}
