#pragma once
// GENERATED by ch06_91_matrix --print against the reference solution.
// Regenerate only when a fixture changes; see tests/public provenance.md.
#include <cstring>
#include <string>

namespace ch06 {

struct GoldenEntry {
    const char* profile;
    const char* fixture;
    const char* digest;
};

// Populated by running the reference solution: ch06_91_matrix --print
// (see tests/public/ch06_chip8_accuracy_debugger/provenance.md).
inline constexpr GoldenEntry kGolden[] = {
    {"COSMAC_VIP", "q1_shift", "0x6367FBD3DFA39E4F"},
    {"CHIP48", "q1_shift", "0x6367FBD3DFA39E4F"},
    {"MODERN", "q1_shift", "0x0DC6375153E01FDC"},
    {"COSMAC_VIP", "q2_loadstore", "0xA800A59848F70230"},
    {"CHIP48", "q2_loadstore", "0xA5BDFCA14BC3C28F"},
    {"MODERN", "q2_loadstore", "0xA5BDFCA14BC3C28F"},
    {"COSMAC_VIP", "q3_jump", "0x044C3DC01263ED1C"},
    {"CHIP48", "q3_jump", "0xD092AF44EC6537E6"},
    {"MODERN", "q3_jump", "0x044C3DC01263ED1C"},
    {"COSMAC_VIP", "q4_draw_wrap", "0xAB4011CADD11AD7D"},
    {"CHIP48", "q4_draw_wrap", "0xBACFBC54E864889E"},
    {"MODERN", "q4_draw_wrap", "0xBACFBC54E864889E"},
    {"COSMAC_VIP", "q5_vfreset", "0x993CE9D4EFCCE802"},
    {"CHIP48", "q5_vfreset", "0x993CE9D4EFCCE802"},
    {"MODERN", "q5_vfreset", "0x498BDC972F9DA959"},
};

// Returns "" when the combination is unknown to the table.
inline std::string golden_for(const std::string& profile,
                              const std::string& fixture) {
    for (const auto& g : kGolden)
        if (g.profile && profile == g.profile && fixture == g.fixture)
            return g.digest;
    return "";
}

}  // namespace ch06
