// Challenge: compose a mixed scene (mode 1: text BG0 + affine BG2, sprites
// with alpha, window) and verify determinism + the committed golden digest.
#define LABSTEST_MAIN
#include <vector>
#include "labstest.hpp"
#include "../05_compositor/ppu.hpp"

using namespace gba;

namespace {

void build_challenge_scene(PpuMemory& m) {
    // Mode 1: BG0 text + BG2 affine. OBJ on, 1D mapping.
    m.wr16(PpuMemory::kIoBase, 0x1F03);
    m.wr16(0x0400004A, 0x003F);  // no windows active -> all visible

    // Backdrop: dark gray.
    m.wr16(PpuMemory::kPalBase + 0, u16(8 | 8 << 5 | 8 << 10));

    // BG0: 256x256 map at block 1, tile 1 = solid teal, prio 1.
    m.wr16(PpuMemory::kIoBase + 8, 1);           // BG0CNT prio1 base0/blk? blk1
    for (int i = 0; i < 32 * 32; ++i)
        m.wr16(0x06000000 + 0x800 + u32(i) * 2, 1);
    for (int r = 0; r < 8; ++r)
        for (int c = 0; c < 4; ++c)
            m.vram[32 + r * 4 + c] = c & 1 ? 0x22 : 0x22;
    m.wr16(PpuMemory::kPalBase + 2 * 2, 0x03E7);  // bank0 color2 = teal-ish

    // Scroll BG0 by (13, 7).
    m.wr16(PpuMemory::kIoBase + 0x10, 13);
    m.wr16(PpuMemory::kIoBase + 0x12, 7);

    // BG2 affine: 128x128 texture, identity matrix, ref point (0, -20).
    m.wr16(PpuMemory::kIoBase + 10, 0);  // BG2CNT prio 0, size bits 0
    for (int ty = 0; ty < 16; ++ty)
        for (int tx = 0; tx < 16; ++tx) {
            m.vram[0x4000 + ty * 16 + tx] = u8(ty * 16 + tx);
            for (int r = 0; r < 8; ++r)
                for (int c = 0; c < 8; ++c)
                    m.vram[u32(ty * 16 + tx) * 64 + r * 8 + c] =
                        u8(((ty * 16 + tx) % 61) + 3);
        }
    m.wr16(PpuMemory::kIoBase + 0x20, 256);  // PA = 1.0
    m.wr16(PpuMemory::kIoBase + 0x26, 256);  // PD = 1.0
    m.io[0x28] = 0xE0;                       // DX = -32 (s32 low byte)
    m.io[0x2A] = 0xFF;

    // Sprite 0: semi-transparent magenta 8x8 at (30,30), prio 1.
    m.oam[0] = 30;
    m.oam[1] = 0x00;              // ATTR0 mode bits are in o[1] bit2-3
    m.oam[1] = 0x04 | 0x08;       // mode 1, 8bpp? keep 4bpp: only mode bits
    m.oam[1] = 0x04;              // mode 1 (semi-transparent)
    m.oam[2] = 30 & 0xFF;
    m.oam[4] = 2;                 // tile 2
    m.oam[5] = 1 << 2;            // priority 1
    for (int i = 0; i < 32; ++i) m.vram[kObjTileBase + 64 + i] = 0x0F;
    m.wr16(PpuMemory::kPalBase + (256 + 15) * 2, 0x7C1F);

    // Alpha blend: first targets BG0+OBJ+BG2 (bits 0,1,2), second backdrop.
    m.wr16(0x04000050, u16(0x07 | (2 << 6) | (0x20 << 8)));
    m.wr16(0x04000052, u16(12 | (6 << 8)));
}

}  // namespace

TEST(challenge, deterministic_and_matches_golden) {
    PpuMemory m;
    build_challenge_scene(m);
    std::vector<u32> a(kScreenW * kScreenH), b(kScreenW * kScreenH);
    compose_frame(m, a.data());
    compose_frame(m, b.data());
    EXPECT_EQ(fnv64(a.data(), a.size() * 4),
              fnv64(b.data(), b.size() * 4));

    // Golden digest generated by the reference solution; see provenance.md.
    const char* kGolden = "7D5D14F3D2397BE5";
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%016llX",
                  (unsigned long long)fnv64(a.data(), a.size() * 4));
    EXPECT_EQ(std::string(buf), std::string(kGolden));
}
