#define LABSTEST_MAIN
#include "labstest.hpp"
#include "chip8.hpp"

#include <vector>

namespace {

using chip8::Chip8;

Chip8 mk(const std::vector<uint8_t>& prog) {
    Chip8 c;
    c.reset();
    c.load(prog);
    return c;
}

void run(Chip8& c, int n) {
    for (int i = 0; i < n && !c.halted; ++i) c.step();
}

}  // namespace

// The LCG must reproduce this exact byte sequence for seed 1 (golden values,
// generated by the reference solution; see tests/public provenance).
TEST(rng, lcg_sequence_is_fixed) {
    Chip8 c;
    c.reset();
    c.seed_rng(1);
    const uint8_t expect[] = {0x6C, 0x82, 0xA5, 0x62, 0xCB, 0x80};
    for (uint8_t e : expect) {
        const uint8_t got = c.next_random();  // single step per expectation
        EXPECT_EQ(got, e);
    }
}

// reset() rewinds the RNG to its default seed - reproducibility by default.
TEST(rng, reset_restores_seed) {
    Chip8 a;
    a.reset();
    const uint8_t first = a.next_random();
    (void)a.next_random();
    (void)a.next_random();
    a.reset();                     // rewind
    const uint8_t again = a.next_random();
    EXPECT_EQ(again, first);

    Chip8 b;
    b.reset();                     // fresh object matches too
    const uint8_t fresh = b.next_random();
    EXPECT_EQ(fresh, first);
}

// CXNN masks the raw byte with NN.
TEST(rng, cxnn_applies_mask) {
    // seed chosen so first byte is 0x6C: CX05 -> 0x6C & 0x05 = 0x04.
    Chip8 c = mk({0xC0, 0x05});
    c.seed_rng(1);
    run(c, 1);
    EXPECT_EQ(c.v[0], 0x04);

    Chip8 d = mk({0xC0, 0xFF});
    d.seed_rng(1);
    run(d, 1);
    EXPECT_EQ(d.v[0], 0x6C);   // full-width mask keeps the whole byte
}

// Two identical seeds give two identical runs (the whole point of seeding).
TEST(rng, same_seed_same_result) {
    Chip8 a = mk({0xC1, 0x0F, 0xC2, 0x0F, 0xC3, 0x0F});
    a.seed_rng(0xFEED);
    run(a, 3);
    Chip8 b = mk({0xC1, 0x0F, 0xC2, 0x0F, 0xC3, 0x0F});
    b.seed_rng(0xFEED);
    run(b, 3);
    EXPECT_EQ(a.v[1], b.v[1]);
    EXPECT_EQ(a.v[2], b.v[2]);
    EXPECT_EQ(a.v[3], b.v[3]);
}

// EXA1 skips when the scripted key is NOT pressed.
TEST(key, exa1_skips_when_not_pressed) {
    Chip8 c = mk({0x61, 0x04,   // VX=4
                  0xE1, 0xA1,   // SKNP V1 -> key4 up -> taken
                  0x62, 0xAA,   // skipped
                  0x63, 0xBB});
    c.key[4] = false;
    run(c, 3);
    EXPECT_EQ(c.v[2], 0);
    EXPECT_EQ(c.v[3], 0xBB);
}

// EX9E skips when it IS pressed.
TEST(key, ex9e_skips_when_pressed) {
    Chip8 c = mk({0x61, 0x04,
                  0xE1, 0x9E,   // SKP V1 -> key4 down -> taken
                  0x62, 0xAA,   // skipped
                  0x63, 0xBB});
    c.key[4] = true;
    run(c, 3);
    EXPECT_EQ(c.v[2], 0);
    EXPECT_EQ(c.v[3], 0xBB);
}

// Register value selects the key through its low nibble: 0x14 -> key 4.
TEST(key, register_nibble_selects_key) {
    Chip8 c = mk({0x61, 0x14,   // V1 = 0x14 -> key 4
                  0xE1, 0x9E,
                  0x62, 0xAA,
                  0x63, 0xBB});
    c.key[4] = true;
    run(c, 2);
    EXPECT_EQ(c.v[2], 0);

    Chip8 d = mk({0x61, 0x14, 0xE1, 0x9E, 0x62, 0xAA, 0x63, 0xBB});
    d.key[5] = true;           // wrong key held -> no skip
    run(d, 4);                 // LD, SKP(no skip), LD witness, LD next
    EXPECT_EQ(d.v[2], 0xAA);
    EXPECT_EQ(d.v[3], 0xBB);
}
